### ISSUE TITLE
2 Data Manipulation Language

### ISSUE THREAD

**Issue by mhaikalla** [bellshade/SQL#26]
Data Manipulation Language (DML):
Berisi tentang operasi yang dilakukan untuk manipulasi data dalam table bisa berupa menghapus, membuat, menampilkan dan modifikasi data, beserta penjelasan dan contoh yang udah ada

Progress File yang sudah terisi materi

- [x] INSERT (Input Datat)
- [x] SELECT (Tampilkan Data)
- [x] DELETE (Menghapus Data)
- [x] UPDATE (Modifikasi Data)

Nanti kalau materi materi nya udah diisi dan dilengkapi, bisa dicentang disini, lalu di PR untuk di review bareng bareng

Ohiya, Jangan lupa di baca rulesnya apa aja sebelum ngisi materi [DISINI](https://github.com/bellshade/SQL/blob/main/CONTRIBUTING.md)

Thank you SQL-Team

**Comment by AdityaFitrianaNS** [comment]
Task Done.
