### ISSUE TITLE
3 Data Definition Language

### ISSUE THREAD

**Issue by mhaikalla** [bellshade/SQL#27]
Data Definition Language DDL:
Berisi tentang Operasi yang dilakukan object bisa berupa table, view atau database, dan berupa penjelasan penjelasan beserta contoh contoh nya

Progress File yang sudah terisi materi

- [x] Create (Membuat Object)
- [x] Show (Menampilkan Object)
- [x] Drop (Menghapus Object)
- [x] ALTER (Modifikasi Object)
- [x] Use (Menggunakan Object)
- [x] Rename (Mengganti Nama Object)

Tolong diisi materi materi nya dan dilengkapi yaa, dan kalau sudah lengkap bisa dicentang disini, lalu di PR untuk di review 

Jangan lupa di baca rulesnya apa aja sebelum ngisi materi [DISINI](https://github.com/bellshade/SQL/issues/38)

Thank you SQL-Team

**Comment by mhaikalla** [comment]
Data Definition Language DDL:
Berisi tentang Operasi yang dilakukan object bisa berupa table, view atau database

1. [ ] Create (Membuat Object)
2. [ ] Show (Menampilkan Object)
3. [ ] Drop (Menghapus Object)
4. [ ] ALTER (Modifikasi Object)
5. [ ] Use (Menggunakan Object)

**Comment by AdityaFitrianaNS** [comment]
Task Done.
