### ISSUE TITLE
1 Pengenalan

### ISSUE THREAD

**Issue by mhaikalla** [bellshade/SQL#28]
Di materi ini menjelaskan tentang pengenalan konsep-konsep dasar dari:

 - [x] Pengenalan Data dan Basis
 - [x] Pengenalan Database
 - [x] Pengenalan Relational Database
 - [x] Kekurangan dan Keuntungan DBMS
 - [x] Contoh DBMS

Persiapan software stack yang dibutuhkan:
Git bash atau SourceTree dan VSCode

**Comment by AdityaFitrianaNS** [comment]
Task Done.
