### ISSUE TITLE
4 Data Control Language

### ISSUE THREAD

**Issue by mhaikalla** [bellshade/SQL#29]
Data Control Language (DCL):
Berisi tentang operasi yang dilakukan untuk mengontrol server pada database beserta data yang ada didalam nya , seperti manipulasi hak akses server dan lainnya

Progress File yang sudah terisi materi

- [x] Grant (Menerima Akses)
- [x] Revoke (Menolak Akses)
Kalau ada yang kurang bisa ditambah sendiri

Nanti kalau materi materi nya udah diisi dan dilengkapi, bisa dicentang disini, lalu di PR untuk di review bareng bareng

Ohiya, Jangan lupa di baca rulesnya apa aja sebelum ngisi materi [DISINI](https://github.com/bellshade/SQL/issues/38)

Thank you SQL-Team

**Comment by fairusatoir** [comment]
Yang ini ku kerjain om @mhaikalla

**Comment by fairusatoir** [comment]
Done 

- [x] Grant (Menerima Akses)
- [x] Revoke (Menolak Akses)
