### ISSUE TITLE
6 Numeric Functions

### ISSUE THREAD

**Issue by mhaikalla** [bellshade/SQL#31]
Progress File yang sudah terisi materi

- [x] 1_Math_Count
- [x] 2_Math_Average
- [x] 3_Math_MinMax
- [x] 4_Math_Sum
- [x] 5_Math_SQRT
- [x] 6_Math_Round
- [x] 7_Math_Square
- [x] 8_Math_Floor
- [x] 9_Math_Random

Note : Jika belum ada tanda ceklis, artinya materi belum terisi.

**Comment by AdityaFitrianaNS** [comment]
Progress File yang sudah terisi materi

- [ ] 1_Math_Count
- [ ] 2_Math_Average
- [ ] 3_Math_MinMax
- [ ] 4_Math_Sum
- [ ] 5_Math_SQRT
- [ ] 6_Math_Round
- [ ] 7_Math_Square
- [ ] 8_Math_Floor
- [ ] 9_Math_Random

**Comment by fairusatoir** [comment]
Close om @mhaikalla
