### ISSUE TITLE
11 Group By

### ISSUE THREAD

**Issue by mhaikalla** [bellshade/SQL#34]

**Comment by fairusatoir** [comment]
bukanya sudah ya [di sini](https://github.com/bellshade/SQL/blob/main/09_GroupBy/1-GROUP_BY.md)

**Comment by fairusatoir** [comment]
Sudah di kerjain om @mhaikalla di [11_GroupBy](https://github.com/bellshade/SQL/tree/main/Basic/11_GroupBy)
